### ISSUE TITLE
Can't extract token and secret from this: 'SSL is required

### ISSUE THREAD

**Issue by arvalon** [aug-mn/restful-android#13]
Imported the project to Android Studio.
The error in the application when login:

> E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
Process: mn.aug.restfulandroid, PID: 25927
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: org.scribe.exceptions.OAuthException: Response body is incorrect. Can't extract token and secret from this: 'SSL is required
'
at org.scribe.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:41)
at org.scribe.extractors.TokenExtractorImpl.extract(TokenExtractorImpl.java:27)
at org.scribe.oauth.OAuth10aServiceImpl.getRequestToken(OAuth10aServiceImpl.java:42)
at mn.aug.restfulandroid.security.AuthorizationManager.getAuthorizationUrl(AuthorizationManager.java:93)
at mn.aug.restfulandroid.activity.LoginActivity$AuthorizeTask.doInBackground(LoginActivity.java:91)
at mn.aug.restfulandroid.activity.LoginActivity$AuthorizeTask.doInBackground(LoginActivity.java:87)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more

**Comment by hashbrown** [comment]
Based on the commits you can see this project has not been maintained in 5 years and was just an example from the time.  I would not expect this to work with a modern Android Studio project.  I would not recommend following this as an example these days.  Try here instead... 
https://developer.android.com/topic/libraries/architecture/guide.html
If consuming rest services, use Retrofit, http://square.github.io/retrofit/
